# Generated by Django 4.2.6 on 2024-04-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name_category", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Links",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, default="", max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name_supplier", models.CharField(max_length=255)),
                (
                    "image_supplier",
                    models.ImageField(
                        blank=True, null=True, upload_to="supplier_images/", verbose_name="supplier-image"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products_images/", verbose_name="Image-products"
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                (
                    "categories",
                    models.ForeignKey(
                        default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to="products.category"
                    ),
                ),
                ("links", models.ManyToManyField(blank=True, to="products.links")),
                ("suppliers", models.ManyToManyField(to="products.supplier")),
            ],
        ),
        migrations.AddField(
            model_name="links",
            name="supplier",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.supplier"),
        ),
    ]
