# Generated by Django 4.2.6 on 2024-04-12 13:03

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(to="products.category"),
        ),
        migrations.AlterField(
            model_name="products",
            name="suppliers",
            field=modelcluster.fields.ParentalManyToManyField(to="products.supplier"),
        ),
    ]
