# Generated by Django 4.2.6 on 2024-03-02 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Nome")),
                ("email", models.EmailField(max_length=200, verbose_name="E-mail")),
                ("phone", models.CharField(max_length=100, verbose_name="Telefone")),
                ("nif", models.CharField(max_length=9, verbose_name="NIF")),
                ("value", models.CharField(blank=True, default=0, null=True, verbose_name="Valor")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
