# Generated by Django 4.2.6 on 2024-03-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.CharField(default="ola", max_length=200, verbose_name="Morada"),
            preserve_default=False,
        ),
    ]
