# Generated by Django 4.2.6 on 2024-03-02 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quote_number", models.CharField(max_length=100, verbose_name="Número do Orçamento")),
                ("title", models.CharField(max_length=100, verbose_name="Titulo")),
                ("address", models.CharField(max_length=200, verbose_name="Morada")),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name="Valor"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("TERMINADOS", "Terminados"),
                            ("PERDIDOS", "Perdidos"),
                            ("OUTROS", "Outros"),
                            ("EM EXECUÇÃO", "Em execução"),
                        ],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client", verbose_name="Cliente"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
