# Generated by Django 4.2.6 on 2024-04-19 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("project_key", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="PricesQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("cost", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("charged", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("profit_money", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("profit_percentage", models.CharField(blank=True, max_length=255, null=True)),
                ("project_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("services_key", models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
                (
                    "prices_count",
                    models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=15, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SectionQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("project_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "section_count",
                    models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=15, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServicesQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.CharField(blank=True, max_length=255, null=True)),
                ("project_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("section_key", models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
                (
                    "service_count",
                    models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=15, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quote_number", models.CharField(max_length=100, verbose_name="Número do Orçamento")),
                ("image", models.ImageField(blank=True, null=True, upload_to="project_images/", verbose_name="Image")),
                ("title", models.CharField(max_length=100, verbose_name="Titulo")),
                ("address", models.CharField(max_length=200, verbose_name="Morada")),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name="Valor"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CONCLUÍDO", "Concluído"),
                            ("PERDIDO", "Perdido"),
                            ("EM ESPERA", "Em Espera"),
                            ("EM EXECUÇÃO", "Em execução"),
                        ],
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="clients.client", verbose_name="Cliente"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
