# Generated by Django 4.2.6 on 2024-05-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricesquote",
            name="section_key",
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True),
        ),
    ]
