# Generated by Django 4.2.6 on 2024-05-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_pricesquote_section_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricesquote",
            name="prices_count",
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="pricesquote",
            name="section_key",
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="pricesquote",
            name="services_key",
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
    ]
