# Generated by Django 4.2.6 on 2024-05-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_alter_pricesquote_prices_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sectionquote",
            name="section_count",
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="servicesquote",
            name="section_key",
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name="servicesquote",
            name="service_count",
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=15, null=True),
        ),
    ]
