# Generated by Django 4.2.6 on 2024-05-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_sectionquote_section_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricesquote",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sectionquote",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="servicesquote",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
