# Generated by Django 4.2.6 on 2024-03-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0006_alter_project_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="state",
            field=models.CharField(
                choices=[
                    ("CONCLUÍDO", "CONCLUIDO"),
                    ("PERDIDO", "Perdido"),
                    ("EM ESPERA", "Em Espera"),
                    ("EM EXECUÇÃO", "Em execução"),
                ],
                max_length=20,
                verbose_name="Estado",
            ),
        ),
    ]
