# Generated by Django 4.2.6 on 2024-04-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0009_project_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="project_images/", verbose_name="Image"),
        ),
    ]
