# Generated by Django 4.2.6 on 2024-04-04 17:52

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0010_alter_project_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            (
                                "title",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("name", wagtail.blocks.CharBlock()),
                                        (
                                            "items",
                                            wagtail.blocks.ListBlock(
                                                wagtail.blocks.StructBlock(
                                                    [
                                                        ("name", wagtail.blocks.CharBlock()),
                                                        (
                                                            "prices",
                                                            wagtail.blocks.ListBlock(
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        ("cost", wagtail.blocks.DecimalBlock()),
                                                                        ("price", wagtail.blocks.DecimalBlock()),
                                                                    ]
                                                                )
                                                            ),
                                                        ),
                                                    ]
                                                )
                                            ),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        use_json_field=True,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MyPage",
        ),
    ]
