# Generated by Django 4.2.6 on 2024-04-04 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("projects", "0011_quote_delete_mypage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="id",
        ),
        migrations.AddField(
            model_name="quote",
            name="page_ptr",
            field=models.OneToOneField(
                auto_created=True,
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="wagtailcore.page",
            ),
            preserve_default=False,
        ),
    ]
