# Generated by Django 4.2.6 on 2024-04-04 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_remove_quote_id_quote_page_ptr"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="key",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
