# Generated by Django 4.2.6 on 2024-04-11 09:30

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_quotes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title",
                        wagtail.blocks.StructBlock(
                            [
                                ("name", wagtail.blocks.CharBlock()),
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                ("product", wagtail.blocks.CharBlock()),
                                                ("quantity", wagtail.blocks.CharBlock()),
                                                (
                                                    "prices",
                                                    wagtail.blocks.ListBlock(
                                                        wagtail.blocks.StructBlock(
                                                            [
                                                                ("description", wagtail.blocks.CharBlock()),
                                                                ("price", wagtail.blocks.DecimalBlock()),
                                                                ("charged", wagtail.blocks.DecimalBlock()),
                                                            ]
                                                        )
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
