# Generated by Django 4.2.6 on 2024-04-12 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0017_alter_quote_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quotes",
            name="page_ptr",
        ),
        migrations.DeleteModel(
            name="Quote",
        ),
        migrations.DeleteModel(
            name="Quotes",
        ),
    ]
