# Generated by Django 4.2.6 on 2024-04-12 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0018_remove_quotes_page_ptr_delete_quote_delete_quotes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("project_key", models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="PricesQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("cost", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("charged", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("profit_money", models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ("profit_percentage", models.CharField(blank=True, max_length=255, null=True)),
                ("project_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("services_key", models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SectionQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("project_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "section_count",
                    models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=15, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServicesQuote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("quantity", models.CharField(blank=True, max_length=255, null=True)),
                ("project_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("section_key", models.DecimalField(blank=True, decimal_places=1, max_digits=15, null=True)),
                (
                    "service_count",
                    models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=15, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="price",
            name="item",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="Price",
        ),
        migrations.DeleteModel(
            name="Title",
        ),
    ]
