# Generated by Django 4.2.6 on 2024-04-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0019_notes_pricesquote_sectionquote_servicesquote_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricesquote",
            name="prices_count",
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=15, null=True),
        ),
    ]
