# Generated by Django 4.2.6 on 2024-04-19 15:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.blocks
import wagtail.contrib.routable_page.models
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalInformation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("additional_information_text", models.CharField(blank=True, max_length=255, null=True)),
                ("additional_information_href", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CustomImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "images_cards",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Image",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FooterTitles",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("footer_navigation_title", models.CharField(blank=True, max_length=255, null=True)),
                ("footer_contact_title", models.CharField(blank=True, max_length=255, null=True)),
                ("copyright", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=255, null=True)),
                ("hero_paragraph", wagtail.fields.RichTextField(blank=True, max_length=255, null=True)),
                ("uses_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "uses_image",
                    wagtail.fields.StreamField(
                        [
                            (
                                "image",
                                wagtail.blocks.StructBlock(
                                    [
                                        (
                                            "image_uses",
                                            wagtail.images.blocks.ImageChooserBlock(
                                                help_text="Select an image for each enterprise", required=False
                                            ),
                                        ),
                                        (
                                            "url_uses",
                                            wagtail.blocks.CharBlock(
                                                label="Url Imagem", max_length=255, required=False
                                            ),
                                        ),
                                    ],
                                    label="Image",
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                ("about_title_1", models.CharField(blank=True, max_length=255, null=True)),
                ("about_paragraph_1", models.CharField(blank=True, max_length=255, null=True)),
                ("about_title_2", models.CharField(blank=True, max_length=255, null=True)),
                ("about_paragraph_2", models.CharField(blank=True, max_length=255, null=True)),
                ("about_title_3", models.CharField(blank=True, max_length=255, null=True)),
                ("about_paragraph_3", models.CharField(blank=True, max_length=255, null=True)),
                ("review_title", models.CharField(blank=True, max_length=255, null=True)),
                ("faqs_title", models.CharField(blank=True, max_length=255, null=True)),
                ("action_title", models.CharField(blank=True, max_length=255, null=True)),
                ("action_benefit", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "about_image_1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "about_image_2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "about_image_3",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "hero_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, "wagtailcore.page"),
        ),
        migrations.CreateModel(
            name="WebsitePages",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text_pages", models.CharField(blank=True, max_length=255, null=True)),
                ("pages_href", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewHome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("title_card", models.CharField(blank=True, max_length=255, null=True)),
                ("paragraph_card", models.CharField(blank=True, max_length=500, null=True)),
                ("letters_circle_card", models.CharField(blank=True, max_length=3, null=True)),
                ("name_of_the_person_card", models.CharField(blank=True, max_length=255, null=True)),
                ("function_of_the_person_card", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_home",
                        to="landingpage.homepage",
                    ),
                ),
                (
                    "review_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review_homes",
                        to="landingpage.customimage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FooterContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("information", models.CharField(blank=True, max_length=255, null=True)),
                ("information_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "information_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faqs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("question", models.CharField(blank=True, max_length=255, null=True)),
                ("answer", models.CharField(blank=True, max_length=500, null=True)),
                ("text_href", models.CharField(blank=True, max_length=255, null=True)),
                ("href_url", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="faqs", to="landingpage.homepage"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
