# Generated by Django 4.2.6 on 2023-11-05 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemnav",
            options={"ordering": ["sort_order"]},
        ),
        migrations.AlterField(
            model_name="itemnav",
            name="navbar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="itemsnavbar", to="landingpage.navbar"
            ),
        ),
    ]
