# Generated by Django 4.2.6 on 2023-11-05 00:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0002_alter_itemnav_options_alter_itemnav_navbar"),
    ]

    operations = [
        migrations.AddField(
            model_name="navbar",
            name="items",
            field=wagtail.fields.StreamField(
                [
                    ("label", wagtail.blocks.CharBlock(label="Nome Item", max_length=255, required=False)),
                    ("url", wagtail.blocks.CharBlock(label="Url Item", max_length=255, required=False)),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.DeleteModel(
            name="ItemNav",
        ),
    ]
