# Generated by Django 4.2.6 on 2023-11-05 00:31

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0003_navbar_items_delete_itemnav"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navbar",
            name="items",
            field=wagtail.fields.StreamField(
                [
                    (
                        "item",
                        wagtail.blocks.StructBlock(
                            [
                                ("label", wagtail.blocks.CharBlock(label="Nome Item", max_length=255, required=False)),
                                ("url", wagtail.blocks.CharBlock(label="Url Item", max_length=255, required=False)),
                            ],
                            label="Item",
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
