# Generated by Django 4.2.6 on 2023-11-05 00:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0004_alter_navbar_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="navbar",
            name="sort_order",
        ),
    ]
