# Generated by Django 4.2.6 on 2023-11-05 17:19

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0005_remove_navbar_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="hero_paragraph",
            field=wagtail.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="uses_image",
            field=wagtail.fields.StreamField(
                [
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image_uses",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Select an image for each enterprise", required=False
                                    ),
                                ),
                                (
                                    "url_uses",
                                    wagtail.blocks.CharBlock(label="Url Imagem", max_length=255, required=False),
                                ),
                            ],
                            label="Image",
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="uses_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
