# Generated by Django 4.2.6 on 2023-11-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("landingpage", "0008_homepage_about_image_1_homepage_about_image_2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewHome",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("title_card", models.CharField(blank=True, max_length=255, null=True)),
                ("paragraph_card", models.CharField(blank=True, max_length=500, null=True)),
                ("letters_circle_card", models.CharField(blank=True, max_length=3, null=True)),
                ("name_of_the_person_card", models.CharField(blank=True, max_length=255, null=True)),
                ("function_of_the_person_card", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="homepage",
            name="review_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="CustomImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "images_cards",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
