# Generated by Django 4.2.6 on 2023-11-09 14:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0011_alter_customimage_images_cards"),
    ]

    operations = [
        migrations.CreateModel(
            name="Faqs",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("question", models.CharField(blank=True, max_length=255, null=True)),
                ("answer", models.CharField(blank=True, max_length=500, null=True)),
                ("text_href", models.CharField(blank=True, max_length=255, null=True)),
                ("href_url", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="faqs", to="landingpage.homepage"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
