# Generated by Django 4.2.6 on 2023-11-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0012_faqs"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="action_benefit",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="action_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
