# Generated by Django 4.2.6 on 2023-11-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("landingpage", "0015_homepage_footer_navigation_title_footernavigation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footernavigation",
            name="navigation_url",
        ),
        migrations.AddField(
            model_name="footernavigation",
            name="navigation_text_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
