# Generated by Django 4.2.6 on 2023-11-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0016_remove_footernavigation_navigation_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="footernavigation",
            name="navigation_text_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
