# Generated by Django 4.2.6 on 2023-11-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0018_homepage_footer_contact_title_footercontact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="copyright",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
