# Generated by Django 4.2.6 on 2023-11-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("landingpage", "0019_homepage_copyright"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="faqs_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
